### ISSUE TITLE
Can't change YAML values in an array

### ISSUE THREAD

**Issue by ochrstn** [baloise/gitopscli#148]
In the documentation is an example for changing a value which is part of an array (https://baloise.github.io/gitopscli/commands/deploy/)

```
--values "{frontend.tag: 1.1.0, backend.tag: 1.1.0, backend.env.[0].value: bar}"
```

For me, this results in the following error:

```
gitopscli deploy: error: argument --values: invalid YAML value: '{frontend.tag: 1.1.0, backend.tag: 1.1.0, backend.env.[0].value: bar}'
```

Looks like the underlying YAML library doesn't support the syntax
```
>>> from ruamel.yaml import YAML, YAMLError
>>> YAML().load("{frontend.tag: 1.1.0, backend.tag: 1.1.0, backend.env.[0].value: bar}")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/main.py", line 341, in load
    return constructor.get_single_data()
  File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 111, in get_single_data
    node = self.composer.get_single_node()
  File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/composer.py", line 78, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/composer.py", line 101, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/composer.py", line 138, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/composer.py", line 211, in compose_mapping_node
    while not self.parser.check_event(MappingEndEvent):
  File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/parser.py", line 140, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/parser.py", line 726, in parse_flow_mapping_key
    raise ParserError(
ruamel.yaml.parser.ParserError: while parsing a flow mapping
  in "<unicode string>", line 1, column 1:
    {frontend.tag: 1.1.0, backend.ta ... 
    ^ (line: 1)
expected ',' or '}', but got '['
  in "<unicode string>", line 1, column 55:
     ... backend.tag: 1.1.0, backend.env.[0].value: bar}
                                         ^ (line: 1)
```

I saw in the code that there is some kind of handling for the array syntax (https://github.com/baloise/gitopscli/blob/0c5dad92ca2d6730ad420a683de9fbd72551d1e9/gitopscli/io_api/yaml_util.py#L49)
but it is not possible to pass the YAML loading.

How is this intended to work? 😅

**Comment by christiansiegel** [comment]
Ah, doc is wrong :see_no_evil: 
The key including square brackets needs to be quoted:
invalid yaml: `{frontend.tag: 1.1.0, backend.tag: 1.1.0, backend.env.[0].value: bar}`
valid yaml: `{frontend.tag: 1.1.0, backend.tag: 1.1.0, 'backend.env.[0].value': bar}`

**Comment by ochrstn** [comment]
> Ah, doc is wrong 🙈
> The key including square brackets needs to be quoted:
> invalid yaml: `{frontend.tag: 1.1.0, backend.tag: 1.1.0, backend.env.[0].value: bar}`
> valid yaml: `{frontend.tag: 1.1.0, backend.tag: 1.1.0, 'backend.env.[0].value': bar}`

That solved my problem! Thanks! 👍
