### ISSUE TITLE
Error while parsing .gitops.config.yaml

### ISSUE THREAD

**Issue by joachimprinzbach** [baloise/gitopscli#162]
Can be fixed by using Strings: https://github.com/baloise-incubator/gitops-nginx-demo/commit/510d9ba90febf4de03e6112443a5662d21f79583 

Error:
```gitopscli create-pr-preview --username **** --password **** --git-provider github --git-provider-url https://github.com/ --git-user 'Baloise Incubator' --git-email incubator@baloise.dev --organisation baloise-incubator --repository-name gitops-nginx-demo --pr-id 51
INFO clone: Cloning repository: https://github.com/baloise-incubator/gitops-nginx-demo.git
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/gitopscli/io_api/yaml_util.py", line 20, in yaml_file_load
    return YAML_INSTANCE.load(stream)
  File "/opt/venv/lib/python3.8/site-packages/ruamel/yaml/main.py", line 341, in load
    return constructor.get_single_data()
  File "/opt/venv/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 111, in get_single_data
    node = self.composer.get_single_node()
  File "/opt/venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 78, in get_single_node
    document = self.compose_document()
  File "/opt/venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 101, in compose_document
    node = self.compose_node(None, None)
  File "/opt/venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 138, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/opt/venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 218, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/opt/venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 138, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/opt/venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 211, in compose_mapping_node
    while not self.parser.check_event(MappingEndEvent):
  File "/opt/venv/lib/python3.8/site-packages/ruamel/yaml/parser.py", line 140, in check_event
    self.current_event = self.state()
  File "/opt/venv/lib/python3.8/site-packages/ruamel/yaml/parser.py", line 585, in parse_block_mapping_key
    raise ParserError(
ruamel.yaml.parser.ParserError: while parsing a block mapping
  in "/tmp/gitopscli/c1555293-f3d2-42e7-bcf1-ff6e9bfe0995/repo/.gitops.config.yaml", line 4, column 3
expected <block end>, but found '<scalar>'
  in "/tmp/gitopscli/c1555293-f3d2-42e7-bcf1-ff6e9bfe0995/repo/.gitops.config.yaml", line 4, column 28

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venv/bin/gitopscli", line 33, in <module>
    sys.exit(load_entry_point('gitopscli==4.8.0', 'console_scripts', 'gitopscli')())
  File "/opt/venv/lib/python3.8/site-packages/gitopscli/__main__.py", line 14, in main
    command.execute()
  File "/opt/venv/lib/python3.8/site-packages/gitopscli/commands/create_pr_preview.py", line 59, in execute
    create_preview_command.execute()
  File "/opt/venv/lib/python3.8/site-packages/gitopscli/commands/create_preview.py", line 43, in execute
    gitops_config = self.__get_gitops_config()
  File "/opt/venv/lib/python3.8/site-packages/gitopscli/commands/create_preview.py", line 87, in __get_gitops_config
    return load_gitops_config(self.__args, self.__args.organisation, self.__args.repository_name)
  File "/opt/venv/lib/python3.8/site-packages/gitopscli/commands/common/gitops_config_loader.py", line 13, in load_gitops_config
    gitops_config_yaml = yaml_file_load(gitops_config_file_path)
  File "/opt/venv/lib/python3.8/site-packages/gitopscli/io_api/yaml_util.py", line 22, in yaml_file_load
    raise YAMLException(f"Error parsing YAML file: {file_path}") from ex
gitopscli.io_api.yaml_util.YAMLException: Error parsing YAML file: /tmp/gitopscli/c1555293-f3d2-42e7-bcf1-ff6e9bfe0995/repo/.gitops.config.yaml```

**Comment by christiansiegel** [comment]
Hmm. Two solutions to this one
1. Explicit strings as you already mentioned (we should update the docs)
2. Use `${VAR}` instead of `{VAR}`. This way the brackets are not interpreted as the start of a map (breaking change to the gitops config -> v2)

**Comment by joachimprinzbach** [comment]
for me version 2 would be better; most of the applications have not migrated to v1 so far

**Comment by niiku** [comment]
I would go with ${VAR} as it's anyway a more commonly used string interpolation.
